print( "CustomOption1=", SandboxVars.ISA.CustomOption1 )
print( "CustomOption2=", SandboxVars.MySandboxMod.CustomOption2 )
print( "CustomOption3=", SandboxVars.MySandboxMod.CustomOption3 )
print( "CustomOption4=", SandboxVars.MySandboxMod.CustomOption4 )
print( "CustomOption5=", SandboxVars.MySandboxMod.CustomOption5 )
