print( "CustomOption1=", SandboxVars.ISA.CustomOption1 )
print( "CustomOption2=", SandboxVars.ISA.CustomOption2 )
print( "CustomOption3=", SandboxVars.ISA.CustomOption3 )
print( "CustomOption4=", SandboxVars.ISA.CustomOption4 )
print( "CustomOption5=", SandboxVars.ISA.CustomOption5 )
print( "CustomOption5=", SandboxVars.ISA.CustomOption6 )
