-- THIS FILE WAS AUTOMATICALLY GENERATED BY TileZed
local overlayMap = {}
overlayMap.VERSION = 1
overlayMap["solarmod_tileset_01_36"] = {{ name = "other", tiles = {"solarmod_tileset_01_38", "solarmod_tileset_01_37"} }}

if not TILEZED then
	getContainerOverlays():addOverlays(overlayMap)
end

return overlayMap
